### PR TITLE
add epoch support

### PR DESCRIPTION
**Pull request by smroid**
Add 'Epoch' key to solve's result dict, identifying the epoch of the star catalog. For bsc5 catalog, analyze the file header to determine whether it is 1950 or 2000 (turns out it is 2000); the hip_main and tyc_main catalogs are always 2000.

Also corrects the proper motion calculation for hip_main and tyc_main catalogs. There is a cosine term present in the RA proper motion field to be dealt with; see code comments and cited references.

The bsc5 catalog documentation is unclear w.r.t. the cosine term; I printed out ra/dec for the brightest stars and empirically determined that applying the cosine correction to bsc5 yields results similar to hip_main.

Also added a trivial example program for invoking the generate_database() function.

### CODE REVIEW

**Comment by smroid** [comment]
Because I'm still very confused about Git, I ended up adding to this pull request instead of making a separate pull request.

The additional change is to replace the two TIFF example images with the original eight example images, saved as high quality JPG. The result of running Tetra on these files is very similar:

Solving for image at: /home/pi/projects/tetra3/examples/data/2019-07-29T204726_Alt60_Azi135_Try1.jpg                                                                                                                                                                                                   
Centroids: 48                                                                                                                                                                                                                                                                                          
Solution: {'RA': 286.43726718257045, 'Dec': 28.94456967731847, 'Epoch': 2000, 'Roll': 28.636038004606302, 'FOV': 11.417931718274343, 'distortion': 0.0015664184550912277, 'RMSE': 6.834683727443201, 'Matches': 18, 'Prob': 3.789812250679279e-27, 'T_solve': 718.7213659635745, 'T_extract': 201.1698\
2201579958}                                                                                                                                                                                                                                                                                            
Solving for image at: /home/pi/projects/tetra3/examples/data/2019-07-29T204726_Alt60_Azi135_Try1.tiff                                                                                                                                                                                                  
Centroids: 49                                                                                                                                                                                                                                                                                          
Solution: {'RA': 286.43664457597305, 'Dec': 28.94424551998268, 'Epoch': 2000, 'Roll': 28.63620447486157, 'FOV': 11.420484380330732, 'distortion': 0.0012499569871240212, 'RMSE': 6.378977492194763, 'Matches': 20, 'Prob': 1.5309393918743565e-32, 'T_solve': 615.3265800094232, 'T_extract': 177.5920\
299696736}                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                       
Solving for image at: /home/pi/projects/tetra3/examples/data/2019-07-29T204726_Alt40_Azi45_Try1.jpg                                                                                                                                                                                                    
Centroids: 47                                                                                                                                                                                                                                                                                          
Solution: {'RA': 355.1986386098536, 'Dec': 58.14656355600603, 'Epoch': 2000, 'Roll': 53.31101053814352, 'FOV': 11.430931240895795, 'distortion': 0.0005071055557958085, 'RMSE': 22.6239113050222, 'Matches': 16, 'Prob': 2.5625968867666867e-21, 'T_solve': 1573.042861011345, 'T_extract': 184.855142\
02620834}                                                                                                                                                                                                                                                                                              
Solving for image at: /home/pi/projects/tetra3/examples/data/2019-07-29T204726_Alt40_Azi45_Try1.tiff                                                                                                                                                                                                   
Centroids: 52                                                                                                                                                                                                                                                                                          
Solution: {'RA': 355.20167901341375, 'Dec': 58.147132606094154, 'Epoch': 2000, 'Roll': 53.30626045697792, 'FOV': 11.427280995373389, 'distortion': 0.0008723197975277481, 'RMSE': 18.03585181861384, 'Matches': 15, 'Prob': 7.259171451209313e-19, 'T_solve': 1546.6792960069142, 'T_extract': 178.739\
9019813165}                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                       
Solving for image at: /home/pi/projects/tetra3/examples/data/2019-07-29T204726_Alt40_Azi-45_Try1.tiff                                                                                                                                                                                                  
Centroids: 18                                                                                                                                                                                                                                                                                          
Solution: {'RA': 172.3689268775693, 'Dec': 57.64932646183326, 'Epoch': 2000, 'Roll': 303.4219960334409, 'FOV': 11.425367052646354, 'distortion': 0.0005937219257252148, 'RMSE': 5.7107980724086325, 'Matches': 12, 'Prob': 5.388664340468595e-17, 'T_solve': 505.4807090200484, 'T_extract': 181.67989\
404173568}                                                                                                                                                                                                                                                                                             
Solving for image at: /home/pi/projects/tetra3/examples/data/2019-07-29T204726_Alt40_Azi-45_Try1.jpg                                                                                                                                                                                                   
Centroids: 15                                                                                                                                                                                                                                                                                          
Solution: {'RA': 172.3688350101659, 'Dec': 57.649360109119264, 'Epoch': 2000, 'Roll': 303.42216075812917, 'FOV': 11.425453458908196, 'distortion': 0.0005654330202332062, 'RMSE': 5.780223544920976, 'Matches': 12, 'Prob': 1.0636841671373344e-18, 'T_solve': 512.3680849792436, 'T_extract': 173.508\
88799410313}                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                       
Solving for image at: /home/pi/projects/tetra3/examples/data/2019-07-29T204726_Alt60_Azi-135_Try1.tiff                                                                                                                                                                                                 
Centroids: 29                                                                                                                                                                                                                                                                                          
Solution: {'RA': 240.46409750364563, 'Dec': 28.94066426847466, 'Epoch': 2000, 'Roll': 329.0490912423849, 'FOV': 11.421580984127694, 'distortion': 0.0009747232155051896, 'RMSE': 5.086453859963065, 'Matches': 16, 'Prob': 7.886415920365176e-25, 'T_solve': 235.42711598565802, 'T_extract': 176.5262\
3198227957}                                                                                                                                                                                                                                                                                            
Solving for image at: /home/pi/projects/tetra3/examples/data/2019-07-29T204726_Alt60_Azi-135_Try1.jpg                                                                                                                                                                                                  
Centroids: 28                                                                                                                                                                                                                                                                                          
Solution: {'RA': 240.46394081495475, 'Dec': 28.94037051956811, 'Epoch': 2000, 'Roll': 329.04392763617204, 'FOV': 11.420815226980052, 'distortion': 0.0010723849580511827, 'RMSE': 5.414355116593011, 'Matches': 14, 'Prob': 1.0689741798718572e-19, 'T_solve': 233.29779703635722, 'T_extract': 181.79\
418903309852}                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                       
Solving for image at: /home/pi/projects/tetra3/examples/data/2019-07-29T204726_Alt60_Azi-45_Try1.tiff                                                                                                                                                                                                  
Centroids: 26                                                                                                                                                                                                                                                                                          
Solution: {'RA': 212.21234844889986, 'Dec': 64.20018146830857, 'Epoch': 2000, 'Roll': 268.3268479637901, 'FOV': 11.421358648559654, 'distortion': 0.001367557070830951, 'RMSE': 6.962837869718159, 'Matches': 11, 'Prob': 2.0088296897850652e-13, 'T_solve': 2920.5075630452484, 'T_extract': 177.5612\
1599813923}                                                                                                                                                                                                                                                                                            
Solving for image at: /home/pi/projects/tetra3/examples/data/2019-07-29T204726_Alt60_Azi-45_Try1.jpg                                                                                                                                                                                                   
Centroids: 22                                                                                                                                                                                                                                                                                          
Solution: {'RA': 212.21315252427033, 'Dec': 64.2007320850147, 'Epoch': 2000, 'Roll': 268.3190903758227, 'FOV': 11.421037101898236, 'distortion': 0.0014053046244748933, 'RMSE': 5.814749966370283, 'Matches': 10, 'Prob': 1.5873147027478717e-11, 'T_solve': 2886.2964319996536, 'T_extract': 181.6736\
1698579043}                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                       
Solving for image at: /home/pi/projects/tetra3/examples/data/2019-07-29T204726_Alt60_Azi45_Try1.jpg                                                                                                                                                                                                    
Centroids: 38                                                                                                                                                                                                                                                                                          
Solution: {'RA': 314.6945064027803, 'Dec': 64.22161017635794, 'Epoch': 2000, 'Roll': 89.34637078856684, 'FOV': 11.425694788023266, 'distortion': 0.0019165073746994121, 'RMSE': 55.28480360901921, 'Matches': 20, 'Prob': 1.5309393918743565e-32, 'T_solve': 12.525402999017388, 'T_extract': 183.1892\
0501042157}                                                                                                                                                                                                                                                                                            
Solving for image at: /home/pi/projects/tetra3/examples/data/2019-07-29T204726_Alt60_Azi45_Try1.tiff                                                                                                                                                                                                   
Centroids: 40                                                                                                                                                                                                                                                                                          
Solution: {'RA': 314.69456232635144, 'Dec': 64.22200870458896, 'Epoch': 2000, 'Roll': 89.34700846679192, 'FOV': 11.425320258370025, 'distortion': 0.002071961388260527, 'RMSE': 55.3930231291181, 'Matches': 20, 'Prob': 1.5309393918743565e-32, 'T_solve': 12.528661987744272, 'T_extract': 177.52325\
301989913}                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                       
Solving for image at: /home/pi/projects/tetra3/examples/data/2019-07-29T204726_Alt40_Azi-135_Try1.jpg                                                                                                                                                                                                  
Centroids: 20                                                                                                                                                                                                                                                                                          
Solution: {'RA': 230.6672694774416, 'Dec': 11.034254320129286, 'Epoch': 2000, 'Roll': 332.2805369057474, 'FOV': 11.427081464761004, 'distortion': 0.000246917068400787, 'RMSE': 5.974272590880458, 'Matches': 11, 'Prob': 1.0874556392493516e-14, 'T_solve': 1800.3051899722777, 'T_extract': 182.7517\
1099230647}                                                                                                                                                                                                                                                                                            
Solving for image at: /home/pi/projects/tetra3/examples/data/2019-07-29T204726_Alt40_Azi-135_Try1.tiff                                                                                                                                                                                                 
Centroids: 23                                                                                                                                                                                                                                                                                          
Solution: {'RA': 230.66739233662003, 'Dec': 11.034335489804114, 'Epoch': 2000, 'Roll': 332.2798002569967, 'FOV': 11.425972600310612, 'distortion': 0.0004412960068231486, 'RMSE': 6.25085599263952, 'Matches': 11, 'Prob': 5.272343266214124e-14, 'T_solve': 2156.4554009819403, 'T_extract': 179.8656\
4303282648}                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                       
Solving for image at: /home/pi/projects/tetra3/examples/data/2019-07-29T204726_Alt40_Azi135_Try1.tiff                                                                                                                                                                                                  
Centroids: 27                                                                                                                                                                                                                                                                                          
Solution: {'RA': 296.7582936641513, 'Dec': 11.314123745433058, 'Epoch': 2000, 'Roll': 24.890748403947224, 'FOV': 11.42479970192634, 'distortion': 0.0008573832196341089, 'RMSE': 7.679785545119508, 'Matches': 19, 'Prob': 2.966014389017351e-31, 'T_solve': 1853.5458089900203, 'T_extract': 175.8070\
759824477}                                                                                                                                                                                                                                                                                             
Solving for image at: /home/pi/projects/tetra3/examples/data/2019-07-29T204726_Alt40_Azi135_Try1.jpg                                                                                                                                                                                                   
Centroids: 26                                                                                                                                                                                                                                                                                          
Solution: {'RA': 296.758297423984, 'Dec': 11.314726686581666, 'Epoch': 2000, 'Roll': 24.898842666974964, 'FOV': 11.42486307888197, 'distortion': 0.0008550113800669652, 'RMSE': 8.679395193061032, 'Matches': 19, 'Prob': 1.1011235512336644e-31, 'T_solve': 1448.2405260205269, 'T_extract': 186.2792\
680040002}

**Comment by gustavmpettersson** [comment]
I edited the example a little bit. Thanks for the fixes on the catalogues, seems like there were some wrong assumptions. My understanding is that people wanted a way of setting the epoch the catalogue is propagated to, so it isn't always the year the database is generated.

I think a new argument `epoch` that defaults to 'now', but can also take a desired epoch year (e.g. 2014), or 'none'/None to skip the propagation with proper motions completely. In the latter case, the database property `epoch` will be set to the catalogue epoch, whereas the other cases it will be set to the user-provided epoch.

Thoughts on this?

**Comment by smroid** [comment]
There are two time concepts in play. One is for defining the celestial
coordinate system, and the other is for propagating proper motions.

Catalog proper motion should be propagated to the date of the image to be
solved (typically now, but someone could be trying to solve a historical
image).

For what people usually refer to as "epoch" in this context, they're
referring to the celestial coordinate system. If tetra3 reports the epoch
of the catalog it ingests (and reports solutions in terms of), always 2000
today, then the application can precess the solution to whatever epoch it
is using. But I think most applications will be happy to work with 2000
celestial coordinates.

If we want to allow the user to supply time related arg(s), I'd suggest
'image_date' (defaults to now) for propagating proper motion, and 'epoch'
(defaults to 2000) for the coordinate system in which the solution is to be
given. I don't think we need the latter (as long as we report the catalog
epoch as my PR does); image_date could be useful for some.

-s

**Comment by gustavmpettersson** [comment]
I see, thanks for the explanation. It seems we need to add two properties to the database. Firstly the `epoch_coordinates` as you have implemented now (which should always be 2000 with the supported databases). Secondly an `epoch_positions` that defaults to the year the database is generated ('now'), but that the user can set to 'none' to disable proper motion propagation (it would then be e.g. 1991.25 for hip_main), or specify the year they want.

Open to suggestions on what to name these in a sensible manner

**Comment by smroid** [comment]
Agreed. I'll update the PR along these lines.
-s

**Comment by smroid** [comment]
Refined 'epoch' and 'proper_motion_epoch' logic as discussed.

**Comment by gustavmpettersson** [comment]
I've made some cleanups, including renaming the epochs to `epoch_equinox` and `epoch_proper_motion` consistently. Also regenerated the default database with latest features. Works on my end. Could you please test carefully all options on your end and I will accept the PR. Thanks!

**Pull request merged**
